.TH kwargs 3
.SH NAME
kwargs \- command line argument handling
.SH LIBRARY
kwargs (\fIlibkwargs\fR, \fI\-lkwargs\fR)

.SH DESCRIPTION
Available API man pages:

.TS
l l.
\fBkwargs_classify\fR	Classify each argument in argv
\fBkwargs_create\fR	Create memory necessary for argument classification
\fBkwargs_destroy\fR	Free the memory allocated by \fBkwargs_create\fR
\fBkwargs_get_optional_value\fR	Get the value associated with an optional parameter
\fBkwargs_get_positional_value\fR	Get the value associated with a positional parameter
\fBkwargs_get_required_value\fR	Get the value associated with a required parameter
\fBkwargs_has_flag\fR	Assess whether a flag parameter was used
\fBkwargs_has_optional\fR	Assess whether an optional parameter was used
\fBkwargs_print_classifications\fR	Print a table of arguments and their classification
.TE
