.TH matrix_accdwn 3
.SH NAME
matrix_accdwn \- Calculate the sum of each column of a matrix
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_accdwn (const Matrix * \fImatrix\fR\fB, Matrix * \fIresult\fR\fB);
.SH DESCRIPTION
.B martix_accdwn
calculates the sum of each column of a matrix \fImatrix\fR, returning the resulting row of values in \fIresult\fR.
.SH SEE ALSO
\fBmatrix_accrgt\fR(3), \fBmatrix_accall\fR(3), \fBmatrix\fR(3)
