.TH matrix_zeros 3
.SH NAME
matrix_zeros \- Set all elements of a matrix to 0
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_zeros (Matrix * \fImatrix\fR\fB);\fR
.SH DESCRIPTION
.B martix_zeros
sets all elements of matrix \fImatrix\fR to zero.
.SH SEE ALSO
\fBmatrix_ones\fR(3), \fBmatrix\fR(3)
