.TH matrix_ebesub 3
.SH NAME
matrix_ebesub \- Element\-by\-element subtraction of two matrices
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_ebesub (const Matrix * \fIleft\fR\fB, const Matrix * \fIright\fR\fB, Matrix * \fIresult\fR\fB);\fR
.SH DESCRIPTION
.B matrix_ebesub
calculates the element\-by\-element difference of two matrices \fIleft\fR and \fIright\fR, and puts the result in matrix \fIresult\fR.
.SH SEE ALSO
\fBmatrix_subsca\fR(3), \fBmatrix\fR(3)
