.TH matrix_varall 3
.SH NAME
matrix_varall \- Calculate the variance of all matrix elements
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBfloat matrix_varall (const Matrix * \fImatrix\fR\fB);
.SH DESCRIPTION
.B martix_varall
calculates the variance of all elements of a matrix \fImatrix\fR.
.SH RETURN VALUE
The variance of the entire input matrix \fImatrix\fR.
.SH SEE ALSO
\fBmatrix_vardwn\fR(3), \fBmatrix_varrgt\fR(3), \fBmatrix_sdvall\fR(3), \fBmatrix_sdvdwn\fR(3), \fBmatrix_sdvrgt\fR(3), \fBmatrix\fR(3)
