.TH matrix_testeq 3
.SH NAME
matrix_testeq \- Test whether two matrices are equal within a tolerance
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBbool matrix_testeq (const Matrix * \fIa\fR\fB, const Matrix * \fIb\fR\fB, float \fIeps\fR\fB);\fR
.SH DESCRIPTION
.B martix_testeq
tests whether two matrices \fIa\fR and \fIb\fR are equal within a tolerance \fIeps\fR.
.SH RETURN VALUE
Boolean true if the two matrices \fIa\fR and \fIb\fR are equal within a tolerance \fIeps\fR, boolean false otherwise.
.SH SEE ALSO
\fBmatrix\fR(3)
