.TH matrix_ebediv 3
.SH NAME
matrix_ebediv \- Element\-by\-element division of two matrices
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_ebediv (const Matrix * \fIleft\fR\fB, const Matrix * \fIright\fR\fB, Matrix * \fIresult\fR\fB);\fR
.SH DESCRIPTION
.B matrix_ebediv
calculates the element\-by\-element division of two matrices \fIleft\fR and \fIright\fR, and puts the result in matrix \fIresult\fR.
.SH SEE ALSO
\fBmatrix_divsca\fR(3), \fBmatrix\fR(3)
