.TH matrix_maxrgt 3
.SH NAME
matrix_maxrgt \- Calculate the maximum of each row of a matrix
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_maxrgt (const Matrix * \fImatrix\fR\fB, Matrix * \fIresult\fR\fB);
.SH DESCRIPTION
.B martix_maxrgt
calculates the maximum of each row of a matrix \fImatrix\fR, returning the resulting column of values in \fIresult\fR.
.SH SEE ALSO
\fBmatrix_maxdwn\fR(3), \fBmatrix_maxall\fR(3), \fBmatrix\fR(3)
