.TH matrix 3
.SH NAME
matrix \- Operations on 2-D arrays, which are implemented as dope vectors.
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)

.SH DESCRIPTION
Available API man pages:

.B matrix_accall
Calculate the sum of all matrix elements
.br
.B matrix_accdwn
Calculate the sum of each column of a matrix
.br
.B matrix_accrgt
Calculate the sum of each row of a matrix
.br
.B matrix_addsca
Add a scalar value to a matrix
.br
.B matrix_avgall
Calculate the average of all matrix elements 
.br
.B matrix_avgdwn
Calculate the average of each column of a matrix
.br
.B matrix_avgrgt
Calculate the average of each row of a matrix
.br
.B matrix_bctdwn
Broadcast a row matrix down
.br
.B matrix_bctrgt
Broadcast a column matrix right
.br
.B matrix_create
Create a matrix object in memory
.br
.B matrix_destroy
Free the memory associated with a matrix object
.br
.B matrix_divsca
Divide a matrix by a scalar value
.br
.B matrix_dotpro
Calculate the dot product of two matrices
.br
.B matrix_ebeadd
Element\-by\-element addition of two matrices
.br
.B matrix_ebediv
Element\-by\-element division of two matrices
.br
.B matrix_ebemap
Apply a function to each element of a matrix
.br
.B matrix_ebesub
Element\-by\-element subtraction of two matrices
.br
.B matrix_hadpro
Element\-by\-element multiplication (Hadamard product) of two matrices
.br
.B matrix_hstack
Stack one matrix to the left of another
.br
.B matrix_maxall
Calculate the maximum of all matrix elements
.br
.B matrix_maxdwn
Calculate the maximum of each column of a matrix
.br
.B matrix_maxrgt
Calculate the maximum of each row of a matrix
.br
.B matrix_minall
Calculate the minimum of all elements of a matrix
.br
.B matrix_mindwn
Calculate the minimum of each column of a matrix
.br
.B matrix_minrgt
Calculate the minimum of each row of a matrix
.br
.B matrix_ones
Set all elements of a matrix to 1
.br
.B matrix_print
Print a matrix
.br
.B matrix_scapro
Multiply a matrix with a scalar
.br
.B matrix_sdvall
Calculate the standard deviation of all elements of a matrix
.br
.B matrix_sdvdwn
Calculate the standard deviation of each column of a matrix
.br
.B matrix_sdvrgt
Calculate the standard deviation of each row of a matrix
.br
.B matrix_stzall
TODO
.br
.B matrix_stzdwn
Scale and translate each column of a matrix to have zero mean and unit variance
.br
.B matrix_stzrgt
TODO
.br
.B matrix_subsca
Subtract a scalar from a matrix
.br
.B matrix_testeq
Test whether two matrices are equal within a tolerance
.br
.B matrix_transp
Transpose a matrix
.br
.B matrix_types
TODO
.br
.B matrix_ustzall
TODO
.br
.B matrix_ustzdwn
TODO
.br
.B matrix_ustzrgt
TODO
.br
.B matrix_varall
Calculate the variance of all elements of a matrix
.br
.B matrix_vardwn
Calculate the variance of each column of a matrix
.br
.B matrix_varrgt
Calculate the variance of each row of a matrix
.br
.B matrix_vstack
Stack one matrix one top of another
.br
.B matrix_write
Write a matrix to file
.br
.B matrix_zeros
Set all elements of a matrix to 0
.br
