.TH matrix_hadpro 3
.SH NAME
matrix_hadpro \- Element\-by\-element multiplication (Hadamard product) of two matrices
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_hadpro (const Matrix * \fIleft\fR\fB, const Matrix * \fIright\fR\fB, Matrix * \fIresult\fR\fB);\fR
.SH DESCRIPTION
.B matrix_hadpro
calculates the element\-by\-element product of two matrices \fIleft\fR and \fIright\fR, and puts the result in matrix \fIresult\fR.
.SH SEE ALSO
\fBmatrix_scapro\fR(3), \fBmatrix\fR(3)
