.TH matrix_vstack 3
.SH NAME
matrix_vstack \- Stack two matrices vertically
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_vstack (const Matrix * \fItop\fR\fB, const Matrix * \fIbottom\fR\fB, Matrix * \fIresult\fR\fB);\fR
.SH DESCRIPTION
.B matrix_vstack
vertically stacks an MxN matrix \fItop\fR on top of an PxN matrix \fIbottom\fR, and puts the result in (M+P)xN matrix \fIresult\fR.
.SH SEE ALSO
\fBmatrix_hstack\fR(3), \fBmatrix\fR(3)
