.TH matrix_zero 3
.SH NAME
matrix_zero \- Set all elements of a matrix to 0
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_zero (Matrix * \fImatrix\fR\fB);\fR
.SH DESCRIPTION
.B martix_zero
sets all elements of matrix \fImatrix\fR to zero.
.SH SEE ALSO
\fBmatrix\fR(3)
