.TH matrix_print 3
.SH NAME
matrix_print \- Print a matrix
.SH LIBRARY
matrix (\fIlibmatrix\fR, \fI\-lmatrix\fR)
.SH SYNOPSIS
.B #include \[dq]matrix/matrix.h\[dq]
.br
\fBvoid matrix_print (FILE * \fIstream\fR\fB, const char * \fIvarname\fR\fB, const Matrix * \fImatrix\fR\fB);\fR
.SH DESCRIPTION
.B martix_print
prints a text representation of the matrix \fImatrix\fR to the file descriptor \fIstream\fR, along with the matrix's variable name, \fIvarname\fR.
.SH SEE ALSO
\fBmatrix_write\fR(3), \fBmatrix\fR(3)
